title: Apicurio Registry
description: 'Open Source Schema and API Registry — a CNCF Sandbox project.'
url: 'https://www.apicur.io'
_baseurl: 'https://www.apicur.io'
github_username: apicurio
github_url: https://github.com/apicurio
github_registry_url: https://github.com/apicurio/apicurio-registry
github_registry_url_2: https://github.com/Apicurio/apicurio-registry/tree/2.6.x
apitomy_url: https://www.apitomy.io
docker_hub_url: https://hub.docker.com/r/apicurio
email: apicurio.registry@redhat.com
future: true
quickstart: true
excerpt_separator: '---'
plugins:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jemoji
sass:
    style: compressed
collections:
    docs: {output: true, permalink: '/docs/:path/'}
defaults:
    - {scope: {type: docs}, values: {layout: docs}}
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:year/:month/:day/:title'}}
    - {scope: {path: ""}, values: {image: {path: /images/opengraph.png, width: 1200, height: 630}}}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
include:
    - _pages
twitter_username: Apicurio
twitter:
    username: Apicurio
